name: sendme
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  google_maps_flutter: ^2.6.1
  permission_handler: ^11.3.1
  http: ^1.2.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.13.0
  connectivity_plus: ^6.0.5
  location: ^6.0.2
  flutter_svg: ^1.1.0
  audioplayers: ^6.1.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_places_flutter: ^2.0.9
  flutter_polyline_points: ^2.1.0
  shared_preferences: ^2.2.3
  uuid: ^4.5.0
  country_code_picker: ^3.0.0
  intl_phone_number_input: ^0.7.4
  intl_phone_field: ^3.2.0
  socket_io_client: ^2.0.3+1
  flutter_datetime_picker: ^1.5.1
  flutter_tts: ^4.0.2
  flutter_local_notifications: ^17.2.3
  path_provider: ^2.1.4
  url_launcher: ^6.3.1
  firebase_messaging: ^15.1.3
  firebase_core: ^3.6.0
  easy_localization: ^3.0.7
  flutter_stripe: ^11.2.0
  flutter_dotenv: ^5.2.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

# To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/cash.png
    - assets/images/profile.png
    - assets/logos/
    - assets/sound/
    - assets/map_theme/aubergine_theme.json
    - assets/map_theme/retro_theme.json
    - assets/map_theme/standard_theme.json
    - assets/map_theme/night_theme.json
    - assets/translations/
    - .env

  # Local Fonts
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic


