// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-PqOvzC6-OUiBDUHmK1uV_S41ozDD4mg',
    appId: '1:128156672205:web:f2d50bdc8885cb107f0984',
    messagingSenderId: '128156672205',
    projectId: 'send-me-431e4',
    authDomain: 'send-me-431e4.firebaseapp.com',
    storageBucket: 'send-me-431e4.firebasestorage.app',
    measurementId: 'G-XZTDSS41BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4mnSZ00uL2imTIZmzPxSf7eNR9EvI8-8',
    appId: '1:128156672205:android:03f69c9003ff919a7f0984',
    messagingSenderId: '128156672205',
    projectId: 'send-me-431e4',
    storageBucket: 'send-me-431e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYEOXicPwKemPZeVcsmH0eoAeCooNOO50',
    appId: '1:128156672205:ios:262bb0756a244d7c7f0984',
    messagingSenderId: '128156672205',
    projectId: 'send-me-431e4',
    storageBucket: 'send-me-431e4.firebasestorage.app',
    iosBundleId: 'com.asynctech.sendme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYEOXicPwKemPZeVcsmH0eoAeCooNOO50',
    appId: '1:128156672205:ios:c95e050b87c331b17f0984',
    messagingSenderId: '128156672205',
    projectId: 'send-me-431e4',
    storageBucket: 'send-me-431e4.firebasestorage.app',
    iosBundleId: 'com.asynctech.sendmeap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-PqOvzC6-OUiBDUHmK1uV_S41ozDD4mg',
    appId: '1:128156672205:web:c0be7fb276f89dac7f0984',
    messagingSenderId: '128156672205',
    projectId: 'send-me-431e4',
    authDomain: 'send-me-431e4.firebaseapp.com',
    storageBucket: 'send-me-431e4.firebasestorage.app',
    measurementId: 'G-Z2LL46P38J',
  );
}
